// SPDX-License-Identifier: MIT OR Apache-2.0
//! Input event handling and interaction tracking.
//!
//! Provides [`InputHandler`] which tracks mouse state (hover, press) across
//! frames and generates [`Interaction`] events by diffing hit-test results.
//!
//! # Example
//!
//! ```
//! use scry_engine::scene::input::{InputHandler, Interaction, MouseButton};
//! use scry_engine::scene::hit::{HitTag, HitTester, HitTestConfig};
//! use scry_engine::scene::style::Point;
//! use scry_engine::scene::{PixelCanvas, Color};
//!
//! let mut canvas = PixelCanvas::new(200, 200);
//! canvas = canvas
//!     .circle(100.0, 100.0, 50.0).fill(Color::RED).done()
//!     .with_tag(HitTag::new(1));
//!
//! let mut handler = InputHandler::new();
//! let tester = HitTester::new(&canvas, HitTestConfig::default());
//!
//! // Simulate mouse move
//! let events = handler.handle_move(Point::new(100.0, 100.0), &tester);
//! assert!(events.iter().any(|e| matches!(e, Interaction::Enter { tag_id: 1 })));
//! ```

use std::collections::HashSet;

use crate::scene::hit::HitTester;
use crate::scene::style::Point;

// ---------------------------------------------------------------------------
// Mouse button
// ---------------------------------------------------------------------------

/// Mouse button identifier.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum MouseButton {
    /// Left mouse button.
    Left,
    /// Right mouse button.
    Right,
    /// Middle mouse button.
    Middle,
}

// ---------------------------------------------------------------------------
// Interaction events
// ---------------------------------------------------------------------------

/// An interaction event generated by the input handler.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum Interaction {
    /// Mouse entered a tagged object's bounds.
    Enter {
        /// The tag ID of the entered object.
        tag_id: usize,
    },
    /// Mouse left a tagged object's bounds.
    Leave {
        /// The tag ID of the left object.
        tag_id: usize,
    },
    /// Mouse hovering over a tagged object.
    Hover {
        /// The tag ID of the hovered object.
        tag_id: usize,
    },
    /// Mouse button pressed on a tagged object.
    Press {
        /// The tag ID of the pressed object.
        tag_id: usize,
        /// Which button was pressed.
        button: MouseButton,
    },
    /// Mouse button released on a tagged object.
    Release {
        /// The tag ID of the released object.
        tag_id: usize,
        /// Which button was released.
        button: MouseButton,
    },
    /// Click: press + release on the same object.
    Click {
        /// The tag ID of the clicked object.
        tag_id: usize,
        /// Which button was clicked.
        button: MouseButton,
    },
}

// ---------------------------------------------------------------------------
// InputHandler
// ---------------------------------------------------------------------------

/// Tracks mouse state and generates interaction events.
///
/// Feed mouse position and button events to the handler each frame.
/// It diffs the current hover set against the previous frame to produce
/// Enter/Leave/Hover events.
pub struct InputHandler {
    /// Set of tag IDs currently under the mouse.
    hover_set: HashSet<usize>,
    /// Set of tag IDs with an active press (button down).
    press_set: HashSet<(usize, MouseButton)>,
    /// Last known mouse position.
    last_pos: Option<Point>,
}

impl InputHandler {
    /// Create a new input handler with no state.
    #[must_use]
    pub fn new() -> Self {
        Self {
            hover_set: HashSet::new(),
            press_set: HashSet::new(),
            last_pos: None,
        }
    }

    /// Handle a mouse move event and return interaction events.
    ///
    /// Performs a hit-test at the given position and computes Enter/Leave/Hover
    /// diffs against the previous hover set.
    pub fn handle_move(&mut self, pos: Point, tester: &HitTester<'_>) -> Vec<Interaction> {
        self.last_pos = Some(pos);
        let hits = tester.test_point(pos);
        let current_ids: HashSet<usize> = hits.iter().map(|h| h.tag_id).collect();

        let mut events = Vec::new();

        // Leave events: was in hover_set but not in current_ids
        for &id in &self.hover_set {
            if !current_ids.contains(&id) {
                events.push(Interaction::Leave { tag_id: id });
            }
        }

        // Enter events: in current_ids but not in hover_set
        for &id in &current_ids {
            if !self.hover_set.contains(&id) {
                events.push(Interaction::Enter { tag_id: id });
            }
        }

        // Hover events for all currently hovered
        for &id in &current_ids {
            events.push(Interaction::Hover { tag_id: id });
        }

        self.hover_set = current_ids;
        events
    }

    /// Handle a mouse button press event.
    pub fn handle_press(
        &mut self,
        pos: Point,
        button: MouseButton,
        tester: &HitTester<'_>,
    ) -> Vec<Interaction> {
        // Also update hover
        let mut events = self.handle_move(pos, tester);

        for &id in &self.hover_set {
            self.press_set.insert((id, button));
            events.push(Interaction::Press { tag_id: id, button });
        }

        events
    }

    /// Handle a mouse button release event.
    pub fn handle_release(
        &mut self,
        pos: Point,
        button: MouseButton,
        tester: &HitTester<'_>,
    ) -> Vec<Interaction> {
        let mut events = self.handle_move(pos, tester);

        for &id in &self.hover_set {
            events.push(Interaction::Release { tag_id: id, button });

            // Click: was pressed and released on same object
            if self.press_set.remove(&(id, button)) {
                events.push(Interaction::Click { tag_id: id, button });
            }
        }

        // Clear any stale presses for this button
        self.press_set.retain(|&(_, b)| b != button);

        events
    }

    /// The set of currently hovered tag IDs.
    #[must_use]
    pub fn hovered(&self) -> &HashSet<usize> {
        &self.hover_set
    }

    /// Whether a specific tag is currently hovered.
    #[must_use]
    pub fn is_hovered(&self, tag_id: usize) -> bool {
        self.hover_set.contains(&tag_id)
    }

    /// Reset all state.
    pub fn reset(&mut self) {
        self.hover_set.clear();
        self.press_set.clear();
        self.last_pos = None;
    }
}

impl Default for InputHandler {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scene::hit::{HitTag, HitTestConfig, HitTester};
    use crate::scene::style::Color;
    use crate::scene::PixelCanvas;

    fn make_scene() -> PixelCanvas {
        let mut canvas = PixelCanvas::new(200, 200);
        canvas = canvas
            .circle(100.0, 100.0, 50.0)
            .fill(Color::RED)
            .done()
            .with_tag(HitTag::new(1));
        canvas = canvas
            .rect(10.0, 10.0, 40.0, 40.0)
            .fill(Color::BLUE)
            .done()
            .with_tag(HitTag::new(2));
        canvas
    }

    #[test]
    fn enter_and_leave_events() {
        let canvas = make_scene();
        let mut handler = InputHandler::new();
        let tester = HitTester::new(&canvas, HitTestConfig::default());

        // Move to circle center
        let events = handler.handle_move(Point::new(100.0, 100.0), &tester);
        assert!(events
            .iter()
            .any(|e| matches!(e, Interaction::Enter { tag_id: 1 })));

        // Move away
        let events = handler.handle_move(Point::new(0.0, 0.0), &tester);
        assert!(events
            .iter()
            .any(|e| matches!(e, Interaction::Leave { tag_id: 1 })));
    }

    #[test]
    fn click_cycle() {
        let canvas = make_scene();
        let mut handler = InputHandler::new();
        let tester = HitTester::new(&canvas, HitTestConfig::default());

        let events = handler.handle_press(Point::new(100.0, 100.0), MouseButton::Left, &tester);
        assert!(events
            .iter()
            .any(|e| matches!(e, Interaction::Press { tag_id: 1, .. })));

        let events = handler.handle_release(Point::new(100.0, 100.0), MouseButton::Left, &tester);
        assert!(events
            .iter()
            .any(|e| matches!(e, Interaction::Click { tag_id: 1, .. })));
    }

    #[test]
    fn hover_state_tracking() {
        let canvas = make_scene();
        let mut handler = InputHandler::new();
        let tester = HitTester::new(&canvas, HitTestConfig::default());

        handler.handle_move(Point::new(30.0, 30.0), &tester);
        assert!(handler.is_hovered(2));
        assert!(!handler.is_hovered(1));
    }
}
